name: facecam
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http:
  uuid: ^3.0.7
  animated_text_kit: ^4.2.2
  firebase_database: ^10.0.4
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.0.2
  google_fonts: ^3.0.1 
  image_picker: ^0.8.6
  tflite: ^1.0.4
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.1
  bottom_navy_bar: ^6.0.0
  profile: ^0.0.1
  flutter_rating_bar: ^4.0.1
  get: ^4.6.5
  camera: ^0.10.5
  shared_preferences: ^2.1.1
  flutter_inappwebview: ^5.7.2+3
  graphql_flutter: ^5.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  
  assets:
    - assets/labels.txt
    - assets/model_unquant.tflite
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf