name: facecam
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  url_launcher: ^6.1.4
  cloud_firestore: ^4.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  http:
  uuid: ^3.0.7
  animated_text_kit: ^4.2.2
  animate_do: ^3.0.2
  firebase_database: ^10.0.4
  firebase_storage_web: ^3.3.14
  video_player: ^2.4.7
  google_fonts: ^3.0.1 
  image_picker: ^0.8.6
  tflite: ^1.0.4
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.2
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  
  assets:
    - assets/image/signin.jpeg
    - assets/labels.txt
    - assets/grayscale_quantized.tflite
    # - assets/trainned/labels.txt
    # - assets/trainned/model_unquant.tflite


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  